### ISSUE TITLE
Validations for Toys

### ISSUE THREAD

**Issue by caseyli** [7chris71000/Bookstore#19]
For this issue, we should add a few validations on toys:

- All toys must have a name
- All toys' serial numbers should be a maximum 20 characters.

**Comment by 7chris71000** [comment]
I'm trying to research how to create a dynamic product page that will be created depending on the product (toy in this case) clicked on in the products list page. I cant seem to find much online and I think this is because I am not using the correct terminology. Every time I have worked on these types of pages  they have already been created and all I did was updates to them. I am wondering if you can provide some key search terms or a link to read more up on this topic. 

If you don't see this before our next meeting or don't have time don't worry about it.

Thanks.

**Comment by 7chris71000** [comment]
Exactly. I have worked with pages that would use something like <%= product.title %> where the title depends on what product the user clicked on in the page preceding.

**Comment by caseyli** [comment]
@7chris71000 ok, so we're kind of building to that with what we call the 'show' page. I'll create an issue for it and start to walk you through it. In the meantime, I've created a couple of more issues assigned to you, and I've commented on the PR associated with this issue.

**Comment by 7chris71000** [comment]
Oh okay thanks. If its something that we haven't got to yet that's okay. It was just something that I remember working with before.

**Comment by caseyli** [comment]
@7chris71000 yeap - we're building to that :)

**Comment by caseyli** [comment]
LGTM!
